/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT 
    COUNTRY,
    COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM Gold.DIM_CUSTOMERS
GROUP BY COUNTRY
ORDER BY TOTAL_CUSTOMERS

-- Find total customers by gender
SELECT 
    GENDER,
    COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM Gold.DIM_CUSTOMERS
GROUP BY GENDER
ORDER BY TOTAL_CUSTOMERS

-- Find total products by category
SELECT 
    CATEGORY,
    COUNT(PRODUCT_ID) AS TOTAL_PRODUCTS
FROM GOLD.DIM_PRODUCTS
GROUP BY CATEGORY
ORDER BY TOTAL_PRODUCTS

-- Find Avg Cost in each category
SELECT
    CATEGORY,
    AVG(COST) AS AVG_COST
FROM GOLD.DIM_PRODUCTS
GROUP BY CATEGORY
ORDER BY AVG_COST

-- Find total revenue generated by each category
SELECT 
    P.CATEGORY,
    SUM(S.SALES_AMOUNT) AS TOTAL_REVENUE
FROM GOLD.FACT_SALES S
LEFT JOIN GOLD.DIM_PRODUCTS P
    ON S.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE

-- Find revenue generated by each customer
SELECT 
    C.CUSTOMER_KEY,
    C.FIRST_NAME,
    C.LAST_NAME,
    SUM(S.SALES_AMOUNT) AS TOTAL_SALES
FROM GOLD.FACT_SALES S
LEFT JOIN GOLD.DIM_CUSTOMERS C
    ON S.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_KEY, C.FIRST_NAME, C.LAST_NAME
ORDER BY TOTAL_SALES DESC

-- Distribution of sold items across countries
SELECT 
    C.COUNTRY,
    SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM GOLD.FACT_SALES S
LEFT JOIN GOLD.DIM_CUSTOMERS C
    ON S.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.COUNTRY
ORDER BY TOTAL_SALES DESC
